# Generated by Django 3.2.9 on 2021-12-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={},
        ),
        migrations.RemoveField(
            model_name='control',
            name='code',
        ),
        migrations.RemoveField(
            model_name='control',
            name='created',
        ),
        migrations.RemoveField(
            model_name='control',
            name='language',
        ),
        migrations.RemoveField(
            model_name='control',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='control',
            name='style',
        ),
        migrations.RemoveField(
            model_name='control',
            name='title',
        ),
        migrations.AddField(
            model_name='control',
            name='book_text',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='control',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='control',
            name='loan_date',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='control',
            name='name_user',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='control',
            name='url_image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
